### PR TITLE
Litecoin Support

### PR DESCRIPTION
**Pull request by hewigovens**

### CODE REVIEW

**Comment by vikmeup** [comment]
@hewigovens @hewig this is exciting! Did you look into node stuff, how big is the difference with btc?

**Comment by hewigovens** [comment]
@vikmeup some apis in bcoin are not working on lcoin, it seems that we have to check source code since I didn't find the rest api docs for lcoin

**Comment by hewigovens** [comment]
could we re-setup codecov? it's better to have coverage report, or change to other service?

**Comment by hewigovens** [comment]
tracked here: https://github.com/TrustWallet/trust-core/pull/89

**Pull request closed without merging**
