### PR TITLE
Slight improvements.

### PR DESCRIPTION
**Pull request by devsedo**
This PR provides slight improvement/shortening to a few places.

`BitcoinPublicKey.swift`
- The idea is to use `switch` for `data.first`. Multiple comparings can be put in a single case.
- `data.first == nil` equals `data.isEmpty` so both these cases can be put in `default` since we need to `return false` in case of being empty and in other unhandled cases as well.

`Data+Hex.swift`
- The idea is to let initializers decide whether to `return nil` or not. Firstly we need to be able to parse UInt8 to ASCII letter. Then this ASCII letter can either be HEX digit or not.
- Joining formatted strings requires less code.

`Function.swift`
- String concatenation with comma-separator can be done more elegant.

### CODE REVIEW

**Comment by vikmeup** [comment]
@devsedo this is great! There is a few changes on this PR: 
https://github.com/TrustWallet/trust-core/pull/29. @alejandro-isaza will take a look at this.

Thanks for contributing.

**Comment by devsedo** [comment]
@vikmeup I was using my own git as a remote so I didn't notice that there was a commit to `master` before making PR :/

**Comment by alejandro-isaza** [comment]
Thanks!

**Comment by vikmeup** [comment]
@devsedo if you have some free time we always have some cool problem to work now. Feel free to ping me on telegram: @vikmeup

**Pull request merged**
